const cars = [
    {
        brand: "Skoda",
        models: [
            "Octavia",
            "Superb",
            "Fabia",
            "Kodiaq",
            "Karoq",
            "Scala",
            "Citigo",
            "Rapid",
            "Yeti",
            "Kamiq",
        ],
    },
    {
        brand: "Volkswagen",
        models: [
            "Golf",
            "Polo",
            "Passat",
            "Tiguan",
            "Jetta",
            "Touareg",
            "Arteon",
            "T-Roc",
            "Up!",
            "Amarok",
        ],
    },
    {
        brand: "Toyota",
        models: [
            "Corolla",
            "Camry",
            "Yaris",
            "Rav4",
            "Prius",
            "Land Cruiser",
            "C-HR",
            "Hilux",
            "Aygo",
            "Supra",
        ],
    },
    {
        brand: "Honda",
        models: [
            "Civic",
            "Accord",
            "CR-V",
            "HR-V",
            "City",
            "Jazz",
            "Pilot",
            "Odyssey",
            "Fit",
            "Insight",
        ],
    },
    {
        brand: "Ford",
        models: [
            "Fiesta",
            "Focus",
            "Mondeo",
            "Escape",
            "Explorer",
            "Ranger",
            "Mustang",
            "Edge",
            "Fusion",
            "EcoSport",
        ],
    },
    {
        brand: "BMW",
        models: [
            "3 Series",
            "5 Series",
            "7 Series",
            "X3",
            "X5",
            "X1",
            "Z4",
            "i3",
            "M4",
            "X7",
        ],
    },
    {
        brand: "Mercedes-Benz",
        models: [
            "C-Class",
            "E-Class",
            "S-Class",
            "GLC",
            "GLE",
            "A-Class",
            "B-Class",
            "G-Class",
            "CLA",
            "GLA",
        ],
    },
    {
        brand: "Audi",
        models: ["A3", "A4", "A6", "Q5", "Q7", "Q3", "TT", "A5", "Q2", "A1"],
    },
    {
        brand: "Hyundai",
        models: [
            "Elantra",
            "Sonata",
            "Santa Fe",
            "Tucson",
            "Kona",
            "Veloster",
            "Accent",
            "Ioniq",
            "Genesis",
            "Palisade",
        ],
    },
    {
        brand: "Nissan",
        models: [
            "Altima",
            "Sentra",
            "Maxima",
            "Rogue",
            "Pathfinder",
            "Murano",
            "Juke",
            "Versa",
            "Leaf",
            "Titan",
        ],
    },
];

export default cars